### ISSUE TITLE
[Bug] Unrecoverable error for no reason

### ISSUE THREAD

**Issue by Delnth** [Mugiwaxar/Mobile-Factory#161]
Screenshot: [Here. (imgur link)](https://i.imgur.com/Y3koFaM.png)

I have no idea what triggers this error. I'm not sure but it seem to happen a lot when I drive into stuff, mostly trees or while driving on transport belts. But I doubt it's that, because I before this error occurred, I had crashed into some of my oil pipes and the game ran fine.

If the screenshot isn't enough to figure out the issue and if it's requested, I can try to pull a list of my mods or even my factorio-current.log file.

I guess the only details I can provide is that I'm playing the game in 1.0 and with Krastorio 2+Space Exploration. Those are the two major mods I have.

**Comment by jacobwatkinsgit** [comment]
Sorry about the fix taking so long. (Discord gets a faster response, I'm almost always on there). Try version 0.0.195, and if that fixes it, Disable the sync area for now if it doesn't. It is one of the buttons in the main GUI with health and energy bars etc.

**Comment by jacobwatkinsgit** [comment]
The bug probably still exists, actually. I was reminded the bug is with the original entity... not the clone. Another mod is destroying the original entity. I could use a modlist and/or save to further investigate (I can without them - it would just take longer and be more frustrating).

**Comment by Mugiwaxar** [comment]
Should be now fixed
Tell me if this still happen
